FROM postgres:12.5-alpine
ADD ./src/db/ctr/ctr_dataset.gz /ctr_dataset.gz
ADD ./src/db/ctr/init-user-db.sh /docker-entrypoint-initdb.d/
ENV POSTGRES_DB=dsp
ENV POSTGRES_USER=dsp
ENV POSTGRES_PASSWORD=dsp
ENV PGDATA=/var/lib/postgresql/data/pgdata