FROM postgres:12.5-alpine
ENV SERVICES_PATH="./services/db-oltp"
ADD $SERVICES_PATH/init-user-db.sh /docker-entrypoint-initdb.d/
ENV POSTGRES_DB=dsp_rtb
ENV POSTGRES_USER=dsp
ENV POSTGRES_PASSWORD=dsp
ENV PGDATA=/var/lib/postgresql/data/pgdata