FROM postgres:12.5-alpine
ADD ./src/db/ads/init-user-db.sh /docker-entrypoint-initdb.d/
ENV POSTGRES_DB=dsp_rtb
ENV POSTGRES_USER=dsp
ENV POSTGRES_PASSWORD=dsp
ENV PGDATA=/var/lib/postgresql/data/pgdata